version: '3.7'
services:
  postgres:
    image: "postgres:15-alpine"
    ports:
      -  "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
      - POSTGRES_DB=app